# Generated by Django 5.0.3 on 2024-03-13 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productscategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'ProductsCategories'},
        ),
    ]
